/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,ts,js}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'bg-primary': 'var(--color-bg-primary)',
        'bg-surface': 'var(--color-bg-surface)',
        'bg-elevated': 'var(--color-bg-elevated)',
        'bg-overlay': 'var(--color-bg-overlay)',
        'border-default': 'var(--color-border-default)',
        'border-active': 'var(--color-border-active)',
        'border-hover': 'var(--color-border-hover)',
        'brand-100': 'var(--color-brand-100)',
        'brand-200': 'var(--color-brand-200)',
        'brand-300': 'var(--color-brand-300)',
        'brand-400': 'var(--color-brand-400)',
        'brand-500': 'var(--color-brand-500)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        'text-inverse': 'var(--color-text-inverse)',
        success: 'var(--color-success)',
        'success-muted': 'var(--color-success-muted)',
        warning: 'var(--color-warning)',
        'warning-muted': 'var(--color-warning-muted)',
        error: 'var(--color-error)',
        'error-muted': 'var(--color-error-muted)',
        info: 'var(--color-info)',
        'info-muted': 'var(--color-info-muted)',
        'platform-x': 'var(--color-platform-x)',
        'platform-youtube': 'var(--color-platform-youtube)',
        'platform-instagram': 'var(--color-platform-instagram)',
        'platform-tiktok': 'var(--color-platform-tiktok)',
        'platform-twitch': 'var(--color-platform-twitch)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
